spring.application.name=rest-soap-web-services
server.port=8080
server.servlet.context-path=/

spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=update

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=876431555574-tnv9v7q1bljptlo9c9rkvjjm1tabr6j1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# GitHub OAuth
spring.security.oauth2.client.registration.github.client-id=Ov23liFqHuOkgQeJBevy
spring.security.oauth2.client.registration.github.client-secret=3af244fb60dadd8120538d007b32c8b3de03de79
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Firebase
firebase.db.url=https://uteq-web-services-default-rtdb.firebaseio.com/

# Heroku
heroku.api-key=HRKU-AA4dieZsycDGFyo-NVVhWzkxtN-TmVSLSwdjOgSjEKkw_____we4mKolj1wp
heroku.app-name=rest-soap-webservices

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/webservices_db
spring.datasource.username=admin1
spring.datasource.password=admin1

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# Enable data.sql execution after table creation
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.uteq.webservices=DEBUG
logging.level.org.springframework.web=INFO

logging.level.org.springframework.ws.client.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.received=DEBUG
logging.level.org.springframework.ws.server.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.server.MessageTracing.received=DEBUG

# SOAP configuration
soap.divisas.url=http://localhost:8080/ws

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=600s

spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=America/Guayaquil

